language: c
dist: trusty
branches:
  only:
    - master

services: mongodb
addons:
  apt:
    update: true
    packages:
      - cmake
      - gcc
      - g++
      - make
      - libgc-dev
      - zlib1g-dev
      - libffi-dev
      - libssl-dev
      - libncurses5-dev
      - curl

before_install:
  - curl https://raw.githubusercontent.com/ktakashi/scheme-env/master/bin/install.sh | bash
  - export PATH=$PATH:~/.scheme-env/bin
  - export MONGODB_RUNNING=yes

install:
  - scheme-env install sagittarius@0.9.2
  - scheme-env install chez@v9.5
  - scheme-env install larceny@1.3
  - find ~/.scheme-env/implementations -maxdepth 3 -type d -exec ls -l {} +

script:
  - ./run-tests.sh
